### PR TITLE
Rsvp Instruments Fix

### PR DESCRIPTION
**Pull request by StevenGrimshaw**
Fix for bug in original rsvp instruments push that had an incorrect many to many relation setup.

### CODE REVIEW

**Review by wyattsmith2023 — APPROVED** [review]

**Review by LukeY23 — COMMENTED** [review]
Did you just delete the rsvp_id from the CreateInstruments migration or is that another migration to get rid of it? I thought that was how the Heroku database was broken before but I'm not sure

**Comment by StevenGrimshaw** [comment]
> 

I changed the original migration of the Instruments database because the rsvp_id that Instruments needed is now stored in the join table InstrumentsRsvps. This should not break the Heroku database because the instruments table does not have information that is important right now.

**Review by ThomasGGoodwin — CHANGES_REQUESTED** [review]
You shouldn't change any of the previous migration files, only add new migrations. I learned this the hard way during sprint 2. They won't translate to the database otherwise unless we reset everything again. I can do that, but I would rather not.

**Review by ThomasGGoodwin — APPROVED** [review]
After looking at the changes to the migrations. I think it will be fine in this case, either way, I'll make sure everything works in the review app and can fix it if it is not okay.

**Pull request merged**
